Handle `platform=None` in `async def before_forward`
trustimaging/stride pull request #57
Opened 2023-10-06 16:01 UTC by charlesincharge

## Motivation

According to `async def before_forward` function documentation, `platform=None` is a valid argument value

```python
        platform : str, optional
            Platform on which to run the operator, ``None`` to run on the CPU or ``nvidia-acc`` to run on
            the GPU with OpenACC. Defaults to ``None``.
```

However, passing in `platform=None` currently raises the following error:

```python
>       save_compression = save_compression if 'nvidia' in platform and devito.pro_available else None
E       TypeError: argument of type 'NoneType' is not iterable

venv/lib/python3.10/site-packages/stride/physics/iso_acoustic/devito.py:274: TypeError
```

## Changes
Add `if platform` check to correctly treat `platform=None` as don't-use-GPU.

2023-10-09 12:45 UTC, ccuetom requested changes

2023-10-09 20:43 UTC, charlesincharge commented on stride/physics/iso_acoustic/devito.py
> +            save_compression = None
Thanks. Both versions produce the same output, but I have followed your suggestion to match the previous code style.

2023-10-09 20:44 UTC, charlesincharge commented
Thanks for the feedback @ccuetom! I have addressed all comments now.

2023-10-09 20:51 UTC, ccuetom approved these changes

2023-10-09 20:55 UTC, ccuetom commented
> Thanks for the feedback @ccuetom! I have addressed all comments now.

Thanks for your contribution!

2023-10-10 10:44 UTC, merged

2023-10-10 15:33 UTC, charlesincharge commented
thanks for the quick turnaround :)